# -*- coding: utf-8 -*-
"""Banking_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FeSvZK1HpEqCfiNJxdsPkGA79Orf_lI
"""

print("Building a Banking Support Chatbot using Machine Learning")
#Import pandas as pd
import pandas as pd
import random
df=pd.read_csv('banking_support_dataset_1000.csv')
df
print('Shape of dataset:')
print(df.shape)
print()
print('We have',df.shape[0],'rows and',df.shape[1],'columns')

#Column names
print(df.columns.tolist())

#Data types
print(df.dtypes)
#Detailed info about DataFrames
df.info()
df.describe()
#Check if values are missing
print('Missing values per column')
print(df.isnull().sum())
print('Sample question:')
print(df['question'][0])
print()
print('Sample response:')
print(df['response'][0])
print()
print('Priority:',df['priority'][0])

import matplotlib.pyplot as plt
#Category distribution
print('Category distribution:')
print(df['category'].value_counts())
print()
print('Total unique categories:',df['category'].nunique())
plt.figure(figsize=(14,5))
df['category'].value_counts().plot(kind='bar',color='steelblue',edgecolor='white')
plt.title('Number of Tickets per category',fontsize=14)
plt.xlabel('Categories')
plt.ylabel('Number of tickets')
plt.xticks(rotation=45,ha='right')
plt.tight_layout()
plt.show()

df['question_length']=df['question'].apply(len)
print('Question length statistics:')
print(df['question_length'].describe().round(1))
print()
print('Shortest Question:')
print(df.loc[df['question_length'].idxmin(),'question'])
print()
print('Longest Question:')
print(df.loc[df['question_length'].idxmax(),'question'])

#Question Distribution
plt.figure(figsize=(10,4))
plt.hist(df['question_length'],bins=10,color='steelblue',edgecolor='white')
plt.title('Distribution of  lengths(number of characters)',fontsize=14)
plt.xlabel('Number of characters')
plt.ylabel('Number of questions')
plt.tight_layout()
plt.show()
print('Average question length by priority')
print(df.groupby('priority')['question_length'].mean().round(1))

#Priority distribution
print('High priority categories:')
print(df[df['priority']=='High']['category'].tolist())
priority_counts=df['priority'].value_counts()
colors=['#e74c3c','#f39c12','#2ecc71']
plt.figure(figsize=(6,6))
plt.pie(priority_counts,labels=priority_counts.index,autopct='%1.1f%%',
        colors=colors,startangle=90)
plt.title('Ticket Priority Distribution',fontsize=14)
plt.tight_layout()
plt.show()

#Import NLTK
import nltk
import re
nltk.download('stopwords',quiet=True)
nltk.download('punkt',quiet=True)
from nltk.corpus import stopwords
english_stopwords=set(stopwords.words('english'))
print('Total english stopwords:',len(english_stopwords))
print()
print('Sample stopwords:')
print(sorted(list(english_stopwords))[:30])

#Define text cleaning function
def clean_text(text):
  text=text.lower()
  text=re.sub(r'[^a-z\s]','',text)
  words=text.split()
  words=[w for w in words if w not in english_stopwords]
  cleaned=' '.join(words)
  return cleaned
print('clean_text function defined')

#Apply the function to all questions
df['clean_question']=df['question'].apply(clean_text)
print('Cleaning applied to all rows')
print()
print('Before and After of first 5 rows:')
print()
for i in range(5):
  print(f'Row{i+1}:')
  print(f'  BEFORE: {df["question"][i]}')
  print(f'  AFTER: {df["clean_question"][i]}')
  print()
df[['question','clean_question','category']].head(10)

#Import TfidfVecorizer from scikit-learn
from sklearn.feature_extraction.text import TfidfVectorizer
#Create the TF-IDF Vectorizer
vectorizer=TfidfVectorizer(max_features=500)
X=vectorizer.fit_transform(df['clean_question'])
print('Shape of X:',X.shape)
print()
print(f'{X.shape[0]} rows=one row per question')
print(f'{X.shape[1]} columns=one column per unique word in the dataset')
y=df['category']
print('Target variable y defined.')
print()
print('y contains the category for each of the 20 questions')
print(y.tolist())
feature_names=vectorizer.get_feature_names_out()
print('Total words in vocabulary:',len(feature_names))
print()
print('First 30 words in alphabetical order:')
print(sorted(feature_names)[:30])
import numpy as np
X_df=pd.DataFrame(X.toarray(),columns=feature_names)
print('TF-IDF matrix-first 5 rows,first 10 columns:')
print('Rows=questions,Columns=words,Values=important scores')
X_df.iloc[:5,:10]
first_question_scores=X_df.iloc[0]
top_words=first_question_scores[first_question_scores>0].sort_values(ascending=False)
print('Original question:',df['question'][0])
print('Cleaned question:',df['clean_question'][0])
print()
print('Top TF-IDF words and scores for tis question:')
print(top_words.head(10))

new_question='my debit card is not working at ATM'
new_question_cleaned=clean_text(new_question)
new_question_vectorized=vectorizer.transform([new_question_cleaned])
print('New question(raw):',new_question)
print('New question(cleaned):',new_question_cleaned)
print('Vectorized shape:',new_question_vectorized.shape)
print()
print('The question is now a row of numbers')

#Import the train-test-split function
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print('Training set size:',X_train.shape)
print('Test set size:',X_test.shape)
print()
print(f'{X_train.shape[0]} questions to train on,{X_test.shape[0]} questions to test on.')
train_categories=sorted(df.loc[y_train.index,'category'].tolist())
test_categories=sorted(df.loc[y_test.index,'category'].tolist())
print('Categories in the training set:')
print(train_categories)
print()
print('Categories in the test set:')
print(test_categories)
print()

#Import Naive Bayes classifier for text data
from sklearn.naive_bayes import MultinomialNB
nb_model=MultinomialNB()
nb_model.fit(X_train,y_train)
print('Naive bayes model trained successfully')
print('The model has learned word-to-category patterns from',X_train.shape[0],'training questions.')
print()
print('Categories the model knows about :')
print(sorted(nb_model.classes_.tolist()))

#Predict categories
test_predictions=nb_model.predict(X_test)
comparison=pd.DataFrame({
    'Actual Category':y_test.values,
     'Predicted Category':test_predictions
})
comparison
live_question='My debit card was declined at the store'
live_question_cleaned=clean_text(live_question)
live_question_vectorized=vectorizer.transform([live_question_cleaned])
live_prediction=nb_model.predict(live_question_vectorized)[0]
live_probabilities=nb_model.predict_proba(live_question_vectorized)[0]
top_3=sorted(zip(nb_model.classes_,live_probabilities),key=lambda pair: -pair[1])[:3]
print('Live question:',live_question)
print('Cleaned version:',live_question_cleaned)
print()
print('Predicted Category:',live_prediction)
print()
print('Top 3 most likely categories with confidence scores:')
for category,score in top_3:
  print(f' {category:12s} {score*100:.1f}%')

#Import evaluation tools
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
test_accuracy=accuracy_score(y_test,test_predictions)
print(f'Test set accuracy: {test_accuracy*100:.1f}%')

#Precision,Recall and F1_score
print('Detailed classification report:')
print(classification_report(y_test,test_predictions,zero_division=0))

#Visualize the confusion matrix as heat map
import seaborn as sns
all_labels=sorted(set(y_test.tolist()) | set(test_predictions.tolist()))
cm=confusion_matrix(y_test,test_predictions,labels=all_labels)
plt.figure(figsize=(6,6))
sns.heatmap(cm,annot=True,fmt='d',cmap='Blues',
            xticklabels=all_labels,yticklabels=all_labels)
plt.title('Confusion Matrix',fontsize=13)
plt.xlabel('Predicted Category')
plt.ylabel('Actual Category')
plt.tight_layout()
plt.show()
model_full=MultinomialNB()
model_full.fit(X,y)
training_predictions=model_full.predict(X)
training_accuracy=accuracy_score(y,training_predictions)
print(f'Training accuracy:{training_accuracy*100:.1f}%')
def get_response_basic(question,model,vectorizer,df):
  cleaned=clean_text(question)
  vector=vectorizer.transform([cleaned])
  predicted_category=model.predict(vector)[0]
  responses = df[df["category"] == predicted_category]["response"].tolist()
  response = random.choice(responses)
  return response,predicted_category
print('The core chatbot logic is complete')
Sample_questions=[
    'How can I check my account balance',
    'My debit card is blocked.',
      'I cannot scan a QR code.',
  ]
for q in Sample_questions:
  response,category=get_response_basic(q,model_full,vectorizer,df)
  print('Question:',q)
  print('Predicted category:',category)
  print('Chatbot response:',response)
  print()
probe_questions=[
    ('Tell me a joke','out-of-scope'),
    ('My account is locked','in-scope'),
    ('What weather is today','out-of-scope'),
    ('Why is my credit card payment not showing','in-scope'),
]
for q,kind in probe_questions:
  cleaned=clean_text(q)
  vec=vectorizer.transform([cleaned])
  proba=model_full.predict_proba(vec)[0]
  top_score=proba.max()
  print(f'[{kind:12s}] top confidence={top_score*100:4.1f}%  question:{q}')
print()
CONFIDENCE_THRESHOLD=0.3
FALLBACK_MESSAGE=("I am sorry.I could not confidently understand your question."
                  "Please call our 24*7 helpline at 1800-149-4647")
def get_response(question,model,vectorizer,df,threshold=CONFIDENCE_THRESHOLD):
  cleaned=clean_text(question)
  vector=vectorizer.transform([cleaned])
  if vector.sum()==0:
    return FALLBACK_MESSAGE,None,0.0
  probabilities=model.predict_proba(vector)[0]
  best_index=probabilities.argmax()
  confidence=probabilities[best_index]
  predicted_category=model.classes_[best_index]
  if confidence<threshold:
    return FALLBACK_MESSAGE,predicted_category,confidence
  response=df[df['category']==predicted_category]['response'].iloc[0]
  return response,predicted_category,confidence
print('get_response() defined')
final_test_questions=[
    'My debit card is blocked.',
    'Tell me a joke',
    'I cannot scan a QR code.',
    'What weather is today',
    'I lost my debit card.'
]
for q in final_test_questions:
  response,category,confidence=get_response(q,model_full,vectorizer,df)
  print('Question:',q)
  print(f'Category:{category}  Confidence:{confidence*100:.1f}%')
  print('Response:',response)
  print()

#Import two new models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
models_to_compare={
    'Naive Bayes':MultinomialNB(),
    'Logistic Regression':LogisticRegression(max_iter=1000),
    'Linear SVM':LinearSVC(max_iter=2000),
}
results={}
for name,model in models_to_compare.items():
  model.fit(X_train,y_train)
  predictions=model.predict(X_test)
  acc=accuracy_score(y_test,predictions)
  results[name]=acc
print('Model comparision on same test set:')
print()
for name,acc in results.items():
  print(f'{name:22s} accuracy={acc*100:.1f}%')

# Install Gradio
!pip install gradio -q

import gradio as gr

# Function for Gradio interface
def chatbot_response(user_question):
    response, category, confidence = get_response(
        user_question,
        model_full,
        vectorizer,
        df
    )
    if category is None:
        category = "Unknown"
    return f"""
Category: {category}
Confidence: {confidence*100:.2f}%

Response:
{response}
"""

# Create interface
demo = gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(
        lines=2,
        placeholder="Ask a banking-related question..."
    ),
    outputs=gr.Textbox(label="Banking Support Chatbot"),
    title="🏦 Banking Support Chatbot",
    description="Enter any banking-related query to receive an AI-generated response."
)

demo.launch()